apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: fullstack-n4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: user
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
