apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-backend
  namespace: fullstack-n4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-backend
  template:
    metadata:
      labels:
        app: spring-boot-backend
    spec:
      containers:
        - name: spring-boot-backend
          image: dylanpion/backend-spring-boot
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://user:password@mongodb:27017/storage
