apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: fullstack-n4
spec:
  selector:
    app: spring-boot-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
