# Fichier combiné
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-backend
  namespace: fullstack-n4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-backend
  template:
    metadata:
      labels:
        app: spring-boot-backend
    spec:
      containers:
        - name: spring-boot-backend
          image: dylanpion/springboot-image
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: fullstack-n4
spec:
  selector:
    app: spring-boot-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
