#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: storage

spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: storage

#mailer-uri: http://localhost:9090/api/mailer/
mailer-uri: http://symfony-mailer-service/api/mailer

BucketProject:
  filestore: /Users/dylanpion/Desktop/filestore
  app:
    jwtSecret: xhxhh137373uddjshkjqshfkjqhkfhilieufizefhiu
    jwtRefreshSecret: jqhkfhilieufizefhiuxhxhh137373uddjshkjqshfhfkjqhkfhilieufizef
    jwtExpirationMs: 60000000
    jwtRefreshExpirationMs: 900000

react:
  host: ${REACT_HOST:localhost}
  port: ${REACT_PORT:5173}