#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: storage

spring:
  data:
    mongodb:
      uri: mongodb.fullstack-n4://user:password@mongodb:27017/storage

BucketProject:
  filestore: /Users/dylanpion/Desktop/filestore
  app:
    jwtSecret: xhxhh137373uddjshkjqshfkjqhkfhilieufizefhiu
    jwtRefreshSecret: jqhkfhilieufizefhiuxhxhh137373uddjshkjqshfhfkjqhkfhilieufizef
    jwtExpirationMs: 60000000
    jwtRefreshExpirationMs: 900000
